// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return const FirebaseOptions(
        apiKey: "AIzaSyBIx4-IqFyruMoN-J9Ue02Ctc1TmRoG7WA",
        authDomain: "quranapp-words1123.firebaseapp.com",
        projectId: "quranapp-words1123",
        storageBucket: "quranapp-words1123.appspot.com",
        messagingSenderId: "155714842480",
        appId: "1:155714842480:web:7cd72164189ec0e6efa9b5",
        databaseURL: "https://quranapp-words1123-default-rtdb.firebaseio.com/",
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnpmkuTarU6ZtrvAstZGbkyLlSLxRd5Ug',
    appId: '1:477965200069:android:10c310e6ef0572d6605eac',
    messagingSenderId: '477965200069',
    projectId: 'flutter-firebase-cli-2023',
    storageBucket: 'flutter-firebase-cli-2023.appspot.com',
    databaseURL: "https://quranapp-words1123-default-rtdb.firebaseio.com/",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyA2XS4xmFMIvrjijyuG7RD-nXBuDbe5cFQ",
    authDomain: "quranapp-words1123.firebaseapp.com",
    projectId: "quranapp-words1123",
    storageBucket: "quranapp-words1123.appspot.com",
    messagingSenderId: "155714842480",
    appId: "1:155714842480:ios:6dd15e68395fde11efa9b5",
    databaseURL: "https://quranapp-words1123-default-rtdb.firebaseio.com",
  );
}
